### ISSUE TITLE
Is it a bug?

### ISSUE THREAD

**Issue by Kiddinglife** [wahern/timeout#19]
in file timeout.c at line 463
if (!(0x1 & pending)) break; /\* break if we didn't wrap around end of wheel */

should we use  T->pending instead of pending ?

**Comment by Kiddinglife** [comment]
i am supposed
 if all slots get expired in a wheel, 
we just stop to save cpu cycles. so we may use T->pending instead of pending

**Comment by Kiddinglife** [comment]
I have spent lot of time on your impl, the bit operation part is pretty hard for me. so maybe I got it wrong.
I am very happy ig you can tell me why I am wrong right here.

**Comment by Kiddinglife** [comment]
i knew why it is pending used. 
when 
thanks.

**Comment by wahern** [comment]
Sorry for not responding earlier.

Hopefully we came to the same conclusion: `pending` is a bitfield that records which slots have expired for a wheel, while `T->pending[wheel]` records which slots have timeouts installed.

I can become paralyzed trying to devise useful names for variables and interfaces. Some people compensate by defaulting to overly long, verbose names. I tend to compensate by using very generic or overly abstract names.

**Comment by Kiddinglife** [comment]
thanks a lot.
