### ISSUE TITLE
timeout_slot() and  timeout_wheel() 

### ISSUE THREAD

**Issue by Kiddinglife** [wahern/timeout#21]
timeout_slot() uses relative timeout to calculate wheel idx, but  timeout_wheel()  uses abs timeout to calculate slot idx. I doubt if this is 100% right. In my opinion, both functions should use relative  timeout

**Comment by wahern** [comment]
You can try it and see what happens. Use the bin64 macro in timeout-debug.h to track the position of the timeout in timeouts_sched:

``` text
 wheel = timeout_wheel(rem);
 slot = timeout_slot(wheel, to->expires);
+SAY("(%p) wheel %d  slot %d (%s)", (void *)to, wheel, slot, bin64(slot));
```

And track the progression of the sweep through the wheels by printing the pending set per wheel in timeouts_update:

``` text
+SAY("wheel[%d] pending %s", wheel, bin64(pending));
+SAY("wheel[%d] populated %s", wheel, bin64(T->pending[wheel]));
 while (pending & T->pending[wheel]) {
```

**Comment by Kiddinglife** [comment]
thank you so much
